### ISSUE TITLE
草泥马，回你的简中去啊 傻逼

### ISSUE THREAD

**Issue by Long-Ni** [yehx1/chatgpt-login#3]

**Comment by yehx1** [comment]
这就是传说中的无能狂怒，忘本

**Comment by yehx1** [comment]
忘本

**Comment by luo-zi** [comment]
> 忘本

引流小鬼反咬一口是吧

**Comment by yehx1** [comment]
https://github.com/Long-Ni/CampusInfo/issues
这是你刚见的项目吧，还没开始写就招来一堆臭骂，可真是牛逼啊
[https://github.com/Long-Ni/CampusInfo/issues](url)
